# Etapa 1: Construcción
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /BestPrice
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: Ejecución
FROM eclipse-temurin:17-jdk
WORKDIR /BestPrice
COPY --from=build /app/target/BestPrice-0.0.1-SNAPSHOT.jar BestPrice.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "BestPrice.jar"]

